---
title: "ППС. Лекция 1"
author: "Anton Gushcha (NCrashed)"
date: "09/05/2014"
output: html_document
---

Балдин Алкександр Викторович, профессор ИУ5.

экзамен

Д.з: описание программного проекта с помощью языка UML 2.0 (12 различных диаграмм). Минимум 6 диаграмм. Любую тему проекта (на полстраницы описание того, что делаем).

Зачем второй вопрос в билете, если не допускаются те, кто не сдает домашнее задание?

Экзамен:

1. Вопросы по домашнему заданию

2. Общие вопросы по дисциплине

Литература
==========

1. Г.Буч Объектно-ориенитированные анализ и проектирвование с примерами приложений на С++, 2е изд. ЭИздательствао Бином, 2001 - 500с.

2. Буч Г., Рамбо Д. Джекобсон А. UML. Руководство пользователя ДМК 2000 432 с

3. Д.Арлоу, А.Нейштадт. UML 2 и унифицированный процесс

4. Дж. Рамбо, М. Блаха Объектно-ориентированное моделирование и разработка - Питер 2007

5. Э.Эванс. Предментно-ориентированное проектирование. Структуризация сложных прогрммных систем.

**6. У Ройс Управление проектами по созаднию программного обеспечения. М. Лори, 2007 -424с**

7. Леоненков А. Скмоучитель UML

8. Леоненков А. Самоучитель UML 2

9 Фокс Дж. Программное обеспечение и его разработка

Проектирование больших программных систем
==============

Главное слово - больших. Большая система - вокруг основной задачи много побочных организационных и не очень подзадач.

Различные области применения - главное в прикладном программировании. Обязательно изучение предметной области.

Промышленные программные продукты:

* Различные области применения

* Сложные в логической организации

* Большие по объему кода

* Имеют много пользователей

* Долгое время жизни (использования)

* Требуеют модернизации и сопровождения

* Должны сопровождаться документацией 

* Разработка ведется коллективом программистов

* Требуют больших финансовых ресурсов

Стадии проектирования программных систем
=========================

1. Формирование требований к системе

2. Проектирование

3. Реализация

4. Тестирование

5. Ввод в эксплуатацию

6. Сопровождение

Каждый шаг может быть откачен назад из-за изменения обстоятельств. Это итерационный процесс.
