---
title: "Топография"
author: '?'
date: "09/30/2014"
output: html_document
---

*Карта* - уменьшенное обобщенное изображение земной поверхности на плоскости, построенное в определенной кратографической проекции с помощью условных знаков.

Виды карт:

* *Топографические* - профессиональные общегеорграфические карты. Генштаб - походы в слабонаселенную местность.

* *Туристические* - менее точные по сравнению с топграфическими, но адаптированные для туристов. Карта Завьялова http://slazav.mccme.ru/maps. Походы в Подмосковьев и соседние области, ММБ, рогейны.

* *Хребтовки* - схемы горной местности

* *Спортивные* - предназначены для спортивного ориентирования

*Масштаб* - отношение линейных размеров объектов на карте к их размерам на местности.


Условные знаки
========

*Масштабные* - размеры на карте связаны с размером на местности через масштаб

*Внемасштабные* - размеры на карте не отражают размеров на местности

*Пояснительные надписи* 

Ориентиры
===

*Точечные* - малые размеры. Могут быть использваны только, если они видны.

*Линейные* - малая ширина, большая протяженность

*Площадные* - большая площадь, наличие контура. 

Надежность ориентировов (ниже менее актуальные):

- Рельеф

- Гидрология

- Магистриальные дороги, железные дороги

- Второстепенные дороги

- Просеки, ЛЭП, газопроводы

- Вырубки, застройка, границы населенных пунктов, тропы


