---
title: "Основы предпринимательства. Лекция 01"
author: "Anton Gushcha (NCrashed)"
date: "09/01/2014"
output: html_document
---

Некрасов Александр Михайлович

- Свои средства

- Свой страх и риск

- Систематический характер

- Создание добавленной стоимости

Нормативно-правовая база в области предпринимательства
------------------------------------------------------

В дз приложение 3 - нужно провести анализ организационной формы предприятия. 

Документы, которые необходимо завтра найти:
- Гражданский кодекс РФ (4 части, но нужна первая часть глава 3 и глава 4)

- Общероссийский классификатор видов экономической деятельности ОКВЭД - предназначен для кодирования, классификации и предоставления информации о видах экономической деятельности.

- ОКФС - общероссийский классифиатор форм собственности

**Частная собственность** - имущество, принадлежащее на праве собственности гражданам и юр. лицам, за исключением отдельных видов имущества, которое в соответствии с законом не может принадлежать гражданам или юр. лицам.

- Общероссийский классификатор оргранизационно правовых форм ОКОПФ (ОКП) - классификация и кодирование организцаионно правовых форм хозяйствующих субъектов.

**Орг. правовой форме** - способ закрепления и использования имущества хоз. субъектов. И вытекающее из этого его правовое положение и цели предпринимательской деятельности. 

Нужно будет проанализировать (приложение 3 дом. задания):
Производственный кооператив
Хозяйственные товарищства (2 вида) (полное и на вере)
Хозяйственные общества (ООО и ОАО, ЗАО)
Индивид. предприниматель

Солидарная ответственность по обязательтсвам - хозяйственные товарщиства, кредиторы требования по каждому в отдельности.

- Федеральный закон об ООО (при создании ООО или ОАО, ЗАО нужно кроме устава еще и протокол собрания учредителей)

- Федеральный закон об произв. кооперативе и об аукционерных обществах

**Найти типовой устав (и протокол собрания учредителей, договор о создании, формы для гос. регистрации)**

Хозяйственные общества
----------------------

Объединение труда и капитала (труд не всегда). Можно не принимать участия в управлении общества. 

Открытое Аукционерное Общество - Число участников не ограничено, можем проводить открытую подписку на выпускаемые акции в свободную продажу (должны соблюдать условия, например: публикация отчетности публично (Форма номер 2 для дз 2 реального предприятия)). Количество и виды ценных бумаг записаны в законе. Можно продавать и покупать никого не спрашивая. Уставной капитал делится на доли и закреляется за акцией. Минимальный размер уставного капитала: 100 000 рублей, прописано законодательно. Управление (например, трехзвенное) - высшее собрание акционеров, совет директоров, исполнительный орган (на основе единачалия, директор, директор-президент (коллегиальный или на основе единоначалия или смесь)). Имеем право создавать наблюдательный совет, только если число участников более 50.

Закрытое Аукционерное Общество - нужно согласовать продажу акций, 

Также нужна расписка о получении документов (в течении 5 дней должны проявить реакцию).

Производственный кооператив - коммерческое предприятие, которое включает в себя признаки и товарищств и обществ (объединение капитала и труда) - или артель. Объединение граждан для выполнения работ, услуг и т.п. Кто может быть членом? (есть некоммерческая версия - потребительский кооператив, отличается только некоммерческой составляющейся). Граждане с 16 летнего возраста, субсидианарная ответственность - право взыскания долга с другого лица, если основное не может его погасить. Не менее 5 членов, все должны предоставлять имущественные средства (денежные, паевые взносы, ценные бумаги). Высшим органом является общее собрание его членов, председатель - исполнительный орган, может быть еще и наблюдательный совет (если число участников большое), текущее руководство - председатель, который может быть членом одного председателя. В наблюдательном органе нельзя совмещать должности. 

Индивидуальное предпринимательство - гражданин РФ или не РФ, который занимается предпринимательской деятельностью от своего имени и несет полную ответственность за результаты этой деятельности, нет образования юридического лица. Если не выполняете свои обязательства, то идет расплата всем своим имуществом. Можно нанимать рабочих, но только в соответствии с ТК.

Унитарные предприятия - муниципиальные и федеральные. На праве хозяйственного ведения и праве оперативного управления. Мы не имеем право их создавать. Уставной капитал делить нельзя, основной собственник - государство. Вопросы создания, реорганизации и ликцвидации - лицо, которое учреждает имеет право.

**ЗАДАНИЕ**
На холдинги нормативные документы. Конкуренция с зарубежными компаними, функции головной компании и т.п. Доклад на 5 минут про холдинги!